name: GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      - run: bun run build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: out

  deploy:
    permissions:
      id-token: write
      pages: write
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v2
